### ISSUE TITLE
WonsikJeong_resume

### ISSUE THREAD

**Issue by onesick** [ga-dc/html_resume#100]
https://gist.github.com/b8d9ecc18cb08f247e85.git

I ran validator but I am keep getting <head> strayed, and <body> block open. However, it seems to me nothing is wrong.

**Comment by jsm13** [comment]
Would you be able to make sure this gist is public. It's not letting me view it. Thanks!

**Comment by onesick** [comment]
I am sorry I don't know why it's giving me the error. It says update public.. when I go into Edit.

**Comment by onesick** [comment]
I think its already a public gist. But it does not work even if I click link

**Comment by onesick** [comment]
https://gist.githubusercontent.com/onesick/b8d9ecc18cb08f247e85/raw/6336e2a031f454a9edfc463bc9bb53dbb5892516/Wonsik_resume
here's a raw link

**Comment by jsm13** [comment]
:+1:  Got it. Nice job on this! So make sure you're only including meta-data in the head. You have [a header and div in your head](https://gist.github.com/onesick/b8d9ecc18cb08f247e85#file-wonsik_resume-L5-L17) which is what is confusing the validator. Validates fine when you move that down into the body. Also be careful of class names like 'block1' try to have something with a bit more specific meaning. 

Could you also add a photo and name to your GitHub profile? Thanks!
