### ISSUE TITLE
Andrew Johnson HTML Resume

### ISSUE THREAD

**Issue by andrewjohnson8819** [ga-dc/html_resume#101]
Gist link: https://gist.github.com/andrewjohnson8819/686f086326be096f2dc4

Fairly straightforward assignment - feeling more comfortable writing HTML without needing to reference dash/prework/in-class lessons.

**Comment by jsm13** [comment]
:+1:  Nice! Really glad you're getting comfortable with HTML.

One note: you can use an unordered list for places like [this](https://gist.github.com/andrewjohnson8819/686f086326be096f2dc4#file-html-resume-L29-L37)

Really happy you're pushing yourself to not go straight to documentation. Not that there's anything wrong with going to the docs but trying from memory first is a great practice to be in. 

Edit:
Also, thanks very much for putting your full name and the exercise clearly in the issue title. That really helps. If you would also include comfort and completeness levels out of five in the issues that would also really help. Thanks!

**Comment by andrewjohnson8819** [comment]
Thanks. I didn't used any lists just because I wasn't sure if that's considered some sort of styling. 

I certainly would add a list instead of all those paragraphs. 

Andrew
