### ISSUE TITLE
Resume_A_Johnson

### ISSUE THREAD

**Issue by ajohnson052** [ga-dc/html_resume#103]
http://htmlpreview.github.io/?https://gist.githubusercontent.com/ajohnson052/87550a291b16d5113727/raw/589d93791855443e5a5560981e4f731afa0fdd92/Resume

https://gist.github.com/ajohnson052/87550a291b16d5113727

Comfort Level: 4
Completeness: 4

This resume could be filled in a bit more, and the structure could still be improved

**Comment by jsm13** [comment]
:+1: Really nice job here! Homework looks great and I really appreciate the comfort/completeness/remarks.

Could you add a name and profile photo to your GitHub account? Thanks!
