### ISSUE TITLE
Mohamed G resume

### ISSUE THREAD

**Issue by MohamedGood** [ga-dc/html_resume#104]
3 out of 5 fist of five

https://gist.github.com/a9b77939b8325fe4c620.git

**Comment by MohamedGood** [comment]
<title></title>
    </head>
    <body>
        <div id="header">
            <p id="name">Mohamed Willis Goodwin</p>
            <a href="mailto:you@yourdomain.com"><p id="email">mohamed.goodwin@gmail.com</p></a>
        </div>
        <div class="left"></div>
        <div class="right">
            <h4>Objective</h4>
            <p>To take a position as a web developer.</p>
            <h4>Experience</h4>
            <p>General Assembly Immersive Course</p>
            <ul>
                <li>Learn and enhance skills on Javascript, CSS, HTML, Ruby, and other relevant software platforms.</li>
                <li>Completed projects with other web developers and UX designers.</li>
            </ul>
            <h4>Skills</h4>
            <p>Languages: C#, JavaScript, Ruby</p>
            <p>Jquery, Ruby on Rails</p>
            <h4>Education</h4>
            <p>BA, History, minor Telecommunications</p>
            <ul>
                <li>Award for Collegiatic All-American</li>
                <li>GPA: 3.4</li>
            </ul>
        </div>
        <div id="footer">
            <p>1225 Kenyon Street NW Washington D.C. 20010</p>
        </div>
    </body>
</html>
 @MohamedGood
 Styling with Markdown is supported

**Comment by ebirving** [comment]
👍
