### ISSUE TITLE
Resume HW Part 1 - QThomas

### ISSUE THREAD

**Issue by qadriyyah119** [ga-dc/html_resume#107]
HTML Review - https://htmlpreview.github.io/?gist.githubusercontent.com/qadriyyah119/5da6c47393ab91b405fa/raw/69568fcc1d4cf9689dfcb33900cc8334ab3b307a/QThomas%2520Resume%2520HM%2520Part%25201

Gist - https://gist.github.com/qadriyyah119/5da6c47393ab91b405fa

comfort_level: 4
completeness: 5

**Comment by nolds9** [comment]
:+1:
