### ISSUE TITLE
Kelly Austin Resume html

### ISSUE THREAD

**Issue by kaustly** [ga-dc/html_resume#109]
Comfort: 3.7
Completeness: 4.7

Comments: I feel like there's more formatting rules I'd like to know, but I can probably learn those on my own time

https://gist.github.com/5b5bc09c6a753ccbccd1.git

**Comment by adambray** [comment]
Hey Kelly,

This looks pretty good. I have two suggestions:
1. Double check your indentation. Specially around lines 11 - 13.
2. Use a `<section>` or other similar tag to group each different job. Right now, the `<h2>` tags are the only thing delineating your different jobs, it'd be nice to group them.

-Adam
