### ISSUE TITLE
Jorge Pimentel HTML Resume

### ISSUE THREAD

**Issue by ghost** [ga-dc/html_resume#110]
Comfort: 5/5
Completeness: 4/5 (incomplete)
My resume is actually pretty long... any suggestions?
https://gist.github.com/jotalp/5ba7b49ad3c6e0f3d2f0

**Comment by mattscilipoti** [comment]
:+1: 
I recommend you use consistent indentation - same number of spaces for each level, each tag that is within another tag should be indented.
Length looks fine.  For now.
