### ISSUE TITLE
Erica Irving- Resume Homework

### ISSUE THREAD

**Issue by ebirving** [ga-dc/html_resume#12]
https://gist.github.com/8d35a285ba6142b50a39.git

Comfort: 4/5
Completeness: 5/5

**Comment by ebirving** [comment]
https://gist.github.com/ebirving/8d35a285ba6142b50a39

**Comment by ebirving** [comment]
Question: When we submit homework to you using gist, do you want to .git link or the regular old web address?

**Comment by RobertAKARobin** [comment]
The regular old web address, please!

You and Adam are both Yaleys.
