### ISSUE TITLE
Erik Anderson Homework #1, Resume

### ISSUE THREAD

**Issue by phantomhaircuts** [ga-dc/html_resume#13]
gist.githubusercontent.com/phantomhaircuts/416c3ea6ed76989e2896/raw/81b4475a313f6661a85995c8b6f89fa58b7fd3ec/resumeHomework

**Comment by RobertAKARobin** [comment]
You weren't allowed to use iframes in this assignment. See the list of "banned" tags and attributes:

https://github.com/ga-dc/html_resume

Also, watch your indentation, which is inconsistent.
