### ISSUE TITLE
Isabella Brookes CV

### ISSUE THREAD

**Issue by isabellabrookes** [ga-dc/html_resume#14]
https://gist.github.com/b6c70a574e3db4d35d5a.git

Comfort: 5/5
Completeness: 5/5

**Comment by RobertAKARobin** [comment]
Isabella, it looks like you made a "private" Gist. Please change it to "public" so I can view it.

**Comment by isabellabrookes** [comment]
It's definitely not "Secret" https://gist.github.com/isabellabrookes/b6c70a574e3db4d35d5a/2afa371cdad44da0b5ed7cd598ee9edbaaed8030

**Comment by isabellabrookes** [comment]
I think I gave you the clone URL, not the real URL - my bad

**Comment by RobertAKARobin** [comment]
Thank you!
