### ISSUE TITLE
Jared Arkin hw1 resume

### ISSUE THREAD

**Issue by jaredarkin** [ga-dc/html_resume#15]
https://gist.github.com/arkinjb/122b252b7bc5ea4afeee

comfort 5
completeness 5

So I'm not sure you'll be able to see my gist. After creating it, when I tried to view it, I got an error- Whoops. We seem to have missed the gist of that gist you're looking for. The gist is still listed under my name so I was able to get the link but I can't get to it.
And apparently github thinks I'm a robot and has hidden my profile. Not sure why. I emailed support when it first happened (around 6:00 pm) but haven't heard back. 
I figured I would submit the link anyway and see what happened. Maybe it'll be fixed by morning.
I could also send you my html file on slack, if you want.
Thanks.

![screen shot 2015-06-29 at 9 41 06 pm](https://cloud.githubusercontent.com/assets/12718947/8422280/9ff4966e-1ea7-11e5-9782-2e21160a3d1b.png)

**Comment by RobertAKARobin** [comment]
Huh. That's a new one. The good news is I can see your Gist and your profile just fine!

I think your divs with the classes of `employment`, `school`, et cetera would make more sense as `h3` tags or something similar: they still introduce the text underneath them.
