### ISSUE TITLE
Mostafa Habib Homework 1 Resume

### ISSUE THREAD

**Issue by M00staff** [ga-dc/html_resume#16]
Comfort 5/5
Completeness 5/5 

Only question is that i couldn't get the 

<a href "mailto:MostafaSHabib@gmail.com">MostafaHabib@gmail.com</a>

to work or validate.  I was hoping to get it to open up an email addressed to me upon click.  Is this because it's not online?

**Comment by RobertAKARobin** [comment]
Please link to your Gist!

**Comment by M00staff** [comment]
duh, sorry!

https://gist.github.com/M00staff/e7fd24ef37c183c6b2e0
