### ISSUE TITLE
HTML Résumé

### ISSUE THREAD

**Issue by silviascript** [ga-dc/html_resume#19]
https://gist.github.com/siltastic/7b4e0fc0d968d12adffb

Comfort Level: 5/5
Completeness: 5/5

This was a pleasant refresher. If we have time in class, could we discuss the differences between the div, article, main, and section tags? I understand the basics for each, but learning to use them appropriately has been confusing in different situations. For example, when should the div tag be used instead of a section tag?

**Comment by RobertAKARobin** [comment]
Good question! I recommend clicking on each and taking a look at their definitions here:

http://www.w3schools.com/tags/

There's generally only one "main" on a page, a couple "sections" and/or "articles", and many "divs".
