### ISSUE TITLE
Kristin Greenslit Resume

### ISSUE THREAD

**Issue by kristingreenslit** [ga-dc/html_resume#20]
https://gist.github.com/kristingreenslit/5af0a2bc34a2a801ffdb

**Comment by RobertAKARobin** [comment]
Instead of `<div><strong>`, a heading `<h3>` would have been more appropriate.

Also, just because you have something inside `<header>` doesn't mean it has to be a heading. The `h2` in your header would make more sense as paragraphs, or better yet, a list.
