### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by englep10** [ga-dc/html_resume#21]
https://gist.githubusercontent.com/englep10/6282c3cb8a6115b49087/raw/f77007ff67bf597eff8b955a50d1dce91ac9b551/gistfile1.txt

comfortably 5/5
complete 5/5

**Comment by RobertAKARobin** [comment]
A list is formatted like this:

```
<ul>
  <li>Thing 1</li>
  <li>Thing 2</li>
  <li>Thing 3</li>
</ul>
```

...rather than a bunch of `<ul>` in a row.
