### ISSUE TITLE
Matt Curtis Resume

### ISSUE THREAD

**Issue by Curtismn87** [ga-dc/html_resume#23]
http://htmlpreview.github.io/?https://gist.github.com/Curtismn87/ba6284995f6069954f0a/raw/a61a327e52e9875059f1cde703f42b5bb403284d/gistfile1.txt

Comfort 5/5
Completeness 5/5

**Comment by RobertAKARobin** [comment]
https://gist.githubusercontent.com/Curtismn87/ba6284995f6069954f0a/raw/a61a327e52e9875059f1cde703f42b5bb403284d

**Comment by RobertAKARobin** [comment]
If all of your `<h2>` have `<strong>` inside them, you don't really need to include the `strong`.
