### ISSUE TITLE
Leigh Varley Resume

### ISSUE THREAD

**Issue by ghost** [ga-dc/html_resume#29]
Gist: https://gist.github.com/leighvarley/32dc4c364b44c167e832

HTML Preview: http://htmlpreview.github.io/?https://gist.githubusercontent.com/leighvarley/32dc4c364b44c167e832/raw/40769c075c2cfd91232a913b7e8c736417294224/Leigh-Varley-Resume.html

Comfort: 4.5
Completeness: 5

Should I have have used div tags?

**Comment by RobertAKARobin** [comment]
Maybe to make individual sections, e.g. one each for Education, Experience, and Community.
