### ISSUE TITLE
Jeff Jones Resume

### ISSUE THREAD

**Issue by jeffjones89** [ga-dc/html_resume#30]
http://htmlpreview.github.io/?gist.githubusercontent.com/jeffjones89/d79cce9a280cb85d4728/raw/660e0013de90933efd9c8b8f810bf7b571facf72/resume.html

Comfort: 5
Completeness: 5

Would be interested to know if spacing in my code is appropriate or not indented enough in certain areas, particularly from a best practice perspective. 'Future me' would be able to follow it, but I'm not sure if it's conventional. 

Thanks!

**Comment by RobertAKARobin** [comment]
It looks great to me!
