### ISSUE TITLE
Adrian Shepelavey Resume HTML

### ISSUE THREAD

**Issue by adrianshep** [ga-dc/html_resume#33]
http://htmlpreview.github.io/?gist.githubusercontent.com/adrianshep/25a20e40006e0af4681c/raw/297ec99da553b92e3a94fd7081141b450679181f/gistfile1.txt

comfort = 5 (not counting motion sickness from doing this on the commuter bus home)
completeness = 5

**Comment by RobertAKARobin** [comment]
Oh, man, don't do that to yourself!
