### ISSUE TITLE
Homework 3 - HTML Resume

### ISSUE THREAD

**Issue by malissaromero** [ga-dc/html_resume#39]
Resume Link: http://htmlpreview.github.io/?https://gist.githubusercontent.com/malissaromero/952a232a969610976751/raw/0bda6716a0899817453b6fc7cd72b68a9e38440e/gistfile1.txt

comfort_level: 3
completeness: 5

I am having trouble understanding the difference between dt and df tags and if they are better at lists than li and ul. 

I am also having trouble with the <meta charset="UTF-8">. I looked it up (http://www.w3schools.com/tags/tag_meta.asp) and the definition is still hard to understand.

**Comment by RobertAKARobin** [comment]
If you were to look up "Google" in an HTML dictionary, it would look like this:

```
<dl>
  <dt>Google</dt>
  <dd>noun: A search engine</dd>
  <dd>verb: To look something up in the Google search engine.</dd>
</dl>
```

`<dt>` (or "definition title") is the word being defined. `<dd>` is the definition.

As for `<meta>`, any character you see on a computer screen is stored somewhere as a sequence of 0s and 1s. There are different "character sets" that have different opinions about which sequence of 0s and 1s should turn into which character. "Unicode Transformation Format", or UTF, is one of those sets. "American Standard Code for Information Interchange", or ASCII, is another.

UTF might say the letter "b" should be stored like this:
00011101
ASCII might say the letter "b" should be stored like this:
11010101
(I'm just making those up.)

Putting that `<meta charset="UTF-8">` in your HTML tells the web browser to use Unicode when it's reading the 0s and 1s that make up your webpage.
