### ISSUE TITLE
Resume Homework

### ISSUE THREAD

**Issue by Ryan-321** [ga-dc/html_resume#41]
URL: https://htmlpreview.github.io/?gist.githubusercontent.com/Ryan-321/38b92d2c0c120e1afc91/raw/d079343d37ea8bfa00b6358e968b05e8a795cad6/gistfile1.txt 

comfort: 4

completeness: 5

Where should we be putting our homework files?  In wdi/exercises?

**Comment by RobertAKARobin** [comment]
Good question! In exercises.
