### ISSUE TITLE
Resume homework

### ISSUE THREAD

**Issue by lanakushnir** [ga-dc/html_resume#43]
comfort : 4
completness : 5

gist : https://gist.github.com/dac28287f9f6df93f583.git

preview : https://htmlpreview.github.io/?gist.githubusercontent.com/lanak1301/dac28287f9f6df93f583/raw/724de390603f00233de5320e49443774934cecc2/gistfile1.txt

**Comment by RobertAKARobin** [comment]
This is pretty short!
