### ISSUE TITLE
link to HTML resume

### ISSUE THREAD

**Issue by LauraWN** [ga-dc/html_resume#48]
https://gist.githubusercontent.com/LauraWN/c5d67c1d9a681784485b/raw/7981efc51ad48030758ff1bf81b8ec6ae9b6f72d/gistfile1.txt

I'm thinking the <h1> tags and then <p> tags need to be indented further.

comfort_level: 4
completeness: 3

**Comment by RobertAKARobin** [comment]
Looks fine to me! I'd like to see more content, though.
