### ISSUE TITLE
tomBeach_resume_homework_day1

### ISSUE THREAD

**Issue by tomBeach** [ga-dc/html_resume#5]
https://gist.github.com/tomBeach/52473e7b45155d33962d

Robin -- wasn't sure if <strong> was allowed (didn't see on NO list so I kept them in...  Hope it's ok!)

**Comment by tomBeach** [comment]
https://gist.github.com/tomBeach/52473e7b45155d33962d
Ooops...  forgot comfort/completeness:  4/5.  (Also, previous comment meant to be "...wasn't sure if 'strong' was allowed...")

**Comment by RobertAKARobin** [comment]
`strong` is allowed because it doesn't necessarily mean things have to be styled a certain way.
