### ISSUE TITLE
Homework #1

### ISSUE THREAD

**Issue by ascreven** [ga-dc/html_resume#52]
https://gist.githubusercontent.com/ascreven/f4b78923806198e60cde/raw/d4aab92c952b389d4d8f1c53bcbee57e77f9a31c/gistfile1.txt

Comfort: 5
Completeness: 5(?)

**Comment by mattscilipoti** [comment]
:+1: Good use of sections, tags, and indentation.

I really had to dig to find a suggestion.  :)  One question to ask yourself, are the `<h3>` tags used to indicate a new section/group of information or did you use them for their formatting?

**Comment by ascreven** [comment]
I think I used them for their formatting. Is that considered formatting with HTML?

**Comment by mattscilipoti** [comment]
Header tags should be used for organization, their formatting is secondary.  I recommend a different tag for the job title.  Maybe `<p class="job-title">Economic Analyst/Business Consultant</p>`.  I could see them used for organization, however, if you had multiple job titles per company.
