### ISSUE TITLE
Eric Stennett HW 1 - HTML Resume

### ISSUE THREAD

**Issue by estennett** [ga-dc/html_resume#55]
Resume Website:

http://htmlpreview.github.io/?https://gist.githubusercontent.com/estennett/ca3a931ee17713275c76/raw/a671c286c1d44ce8c7a5b3d6d006aa0635bde811/gistfile1.txt

Comfort Level: 4
Completeness: 5
I would appreciate feedback on my usage of div tags to organize my HTML.

**Comment by nolds9** [comment]
:+1: I think its an appropriate usage of divs
