### ISSUE TITLE
AleaQ.HW1

### ISSUE THREAD

**Issue by ghost** [ga-dc/html_resume#56]
https://gist.github.com/ScreenName4eva/d574de703264b95bc763

**Comment by mattscilipoti** [comment]
:+1: Looking good.
I recommend that you use indentation to indicate tags contained within other tags.  For example, each `li` within a `ul` should be indented on level.  It makes it much easier to see where a contain begins and ends.
In the future, please include Comfort/Completeness per [submission guidelines](https://github.com/ga-dc/wdi7/blob/master/homework/submission-process.md#what-to-include-with-your-submission)
