### ISSUE TITLE
Rachel Porter Resume Homework

### ISSUE THREAD

**Issue by ddayporter** [ga-dc/html_resume#59]
My Gist: https://gist.github.com/22900e6058fa81c378de

Comfort score, 4.5 out of 5
Completeness score, 4.5 out of 5
I feel pretty good about this code, not sure that the h4 tag was appropriate for the contact info section.

**Comment by mattscilipoti** [comment]
:+1: Looks good.

Agree with you about the h4.  That feels more like supporting information for the header.  I recommend another tag, with an appropriate class(es).
