### ISSUE TITLE
Pengelly - Resume Homework

### ISSUE THREAD

**Issue by jenpen** [ga-dc/html_resume#60]
Preview: 
http://htmlpreview.github.io/?https://gist.githubusercontent.com/jenpen/a6c6c1beb3c7d6192935/raw/200269af80a03d1b9cf9139c689505f54569c2c7/homework01_resume.html

Gist: 
https://gist.github.com/jenpen/a6c6c1beb3c7d6192935

comfort: 4.5 of 5
completeness: 5 of 5 (I think!)

**Comment by andrewsunglaekim** [comment]
:+1:  looks great! thanks jen!
