### ISSUE TITLE
Resume

### ISSUE THREAD

**Issue by tkentor** [ga-dc/html_resume#64]
https://gist.github.com/tkentor/53a11eef7f8d0f57e872

**Comment by jsm13** [comment]
:+1: Overall great job. Great use of semantic class names and it is tidy. Couple things to think on with links referencing your gist:
1. [You can use a heading (headline) tag here - probably a h2](https://gist.github.com/tkentor/53a11eef7f8d0f57e872#file-teddykentorresume-txt-L15). You can put class tags on any element so would just need to switch div to h1 in this instance.
2. [You can use an unordered list with list items here](https://gist.github.com/tkentor/53a11eef7f8d0f57e872#file-teddykentorresume-txt-L15).

Generally you want to be using divs as a container of nested elements which are members of the same logical division. The class on the DOM tomorrow afternoon should show some good examples of the value of nesting.
