### ISSUE TITLE
Resume - Jordan Brauner

### ISSUE THREAD

**Issue by jordanbrauner** [ga-dc/html_resume#66]
https://gist.github.com/jordanbrauner/e0b1d8f79eafde9934da

Comfort: 4
Completeness: 5

**Comment by amaseda** [comment]
:+1:

Some notes...
• I would suggest not using spaces in your class names. While there might be a way to use those properly, as it stands when your div looks like this...

``` html
<div class="Summary of Qualifications">...</div>
```

...it is interpreted as having three separate classes: `Summary`, `of` and `Qualifications`. Instead, you could do something like...

``` html
<div class="summary-of-qualifications">...</div>
```
