### ISSUE TITLE
Starr's Resume

### ISSUE THREAD

**Issue by starrchen** [ga-dc/html_resume#68]
https://gist.github.com/starrchen/f57e6be0c39b3a2475ad

comfort: 5
completeness: 5

**Comment by amaseda** [comment]
:+1: :+1: :+1:

Great job! Couple notes...
• I would avoid creating classes with spaces in the name. `<div class="org name">...</div>` will be interpreted as having two classes: `org` and `name`. Try connecting those words with a `-` instead!
• Make sure to close all your tags. Looks like there's an open `<li>` on Line 24 and `</strong>` on Line 30.
