### ISSUE TITLE
Matt Ficke

### ISSUE THREAD

**Issue by mattficke** [ga-dc/html_resume#7]
https://gist.github.com/mattficke/045372f2ffa1bb82450d

Got these messages in the validator:
1. Info: The Content-Type was text/html. Using the HTML parser.
2. Info: Using the schema for HTML with SVG 1.1, MathML 3.0, RDFa 1.1, and ITS 2.0 support.

What's the best practice for the default info to include in the header? Just wondering if content-type should always be defined, if doctype should specify HTML5 (vs just HTML), etc.

Comfort: 4/5
Completeness: 5/5

**Comment by RobertAKARobin** [comment]
Those are warnings, which are fine. It's only errors that you need to worry about.

Your `<head>` (which I think you meant, instead of `<header>`) is fine the way it is!
