### ISSUE TITLE
Elise Kain: Resume

### ISSUE THREAD

**Issue by elisekain** [ga-dc/html_resume#71]
completeness: 5
comfort_level: 4

https://gist.github.com/elisekain/61182186c8a42c586be2

**Comment by jsm13** [comment]
:+1:  Excellent job! Just a couple thoughts:
- You can get rid of [empty elements](https://gist.github.com/elisekain/61182186c8a42c586be2#file-elisekain_resume-html-L114). 
- Maybe put sections like [education](https://gist.github.com/elisekain/61182186c8a42c586be2#file-elisekain_resume-html-L24-L36) in divs if it ends up helping format.
