### ISSUE TITLE
Ly's Resume

### ISSUE THREAD

**Issue by Ly900** [ga-dc/html_resume#73]
https://gist.githubusercontent.com/Ly900/0af57f1b4d16e3a47d6d/raw/7e5ce14adeecbf622def284f097ab1268b635d9e/gistfile1.txt

Comfort: 4
Completeness: 5 

I am wondering if the footer is really necessary for every HTML page. Are there basic element requirements for webpages using HTML 5? 

Should I remove the trainings/classes I've done for web development?

**Comment by andrewsunglaekim** [comment]
:+1:  No footers aren't neccessary. It's just a semantic container for information that goes at the bottom of a page. I wouldn't worry too much about what to put on your resume for web development until like week 10-12. Great job!
