### ISSUE TITLE
HTML Resume homework

### ISSUE THREAD

**Issue by mooniker** [ga-dc/html_resume#74]
https://gist.githubusercontent.com/mooniker/dd7d7150354a25c1b750/raw/98dc720e5d25177abaebc3d834fdf57079159976/resume.html
https://gist.github.com/mooniker/dd7d7150354a25c1b750

Comfort: 4-5 (due to less familiarity with the new semantic HTML5 stuff), Completeness 4 out of 5. No questions.

**Comment by andrewsunglaekim** [comment]
:+1:  looks great thanks james!
