### ISSUE TITLE
HTML Resume Homework 

### ISSUE THREAD

**Issue by beckybeauchamp1** [ga-dc/html_resume#78]
comfort_level: 4
completeness: 5

https://gist.github.com/beckybeauchamp1/6a1dbabc96d083c08a07

**Comment by adambray** [comment]
Great job! I honestly can't really find any suggestions on how to improve your markup! The only thing I noticed is that you put spaces between the attributes and their values. Common style would be:

``` html
<div class="education">
```

as opposed to:

``` html
<div class =  "education>
```

-Adam
