### ISSUE TITLE
Tyler Crosse's Resume

### ISSUE THREAD

**Issue by tylercrosse** [ga-dc/html_resume#79]
Link to gist: https://gist.github.com/tylercrosse/e55d36e7cad6f0a0d453

Comfort: 4.5/5
Completeness: 4.5/5

Not important:
I'm going to try to meet with someone to figure this out. I ran into a lot of trouble trying to get my 'github pages' repo to work correctly. Before this assignment I was using that repo ('tylercrosse.github.io') to host my personal site but removed it for this. The only thing in there right now is the index.html file containing my resume. I also had the address tylercrosse.github.io to redirect to my domain tylercrosse.com. I think this might be the source of my problems.  Thanks!

**Comment by amaseda** [comment]
:+1:

If you still need help with Github pages let me know. Can talk about that later today (or Monday). Let me know. But you're probably right - might have something to do with the redirect.
