### ISSUE TITLE
Aurelio Avelleyra Resume

### ISSUE THREAD

**Issue by aoave** [ga-dc/html_resume#80]
https://gist.github.com/b6a11180b5a7b556aa4f.git

Comfort level:3
Completeness:3

Just want a little more understanding of terms and when to use them

**Comment by adambray** [comment]
Hey!

This looks good. My main suggestion would be not to rely so heavily on `<hX>` tags (e.g. h3, h4, etc). Generally most documents shouldn't go beyond h3, maybe h4s. Instead, try using section tags + paragraph tags to delineate different lower levels of text.

-Adam
