### ISSUE TITLE
Mia Grodsky Resume

### ISSUE THREAD

**Issue by mcgrodsky** [ga-dc/html_resume#83]
Link to code - https://gist.githubusercontent.com/mcgrodsky/c88531a7cabdc7c10f90/raw/8d440e5860477e3cff3c23ba55a5d3f2ecf02bcc/miagrodskyresume.html

link to resume- http://htmlpreview.github.io/?https://gist.githubusercontent.com/mcgrodsky/c88531a7cabdc7c10f90/raw/8d440e5860477e3cff3c23ba55a5d3f2ecf02bcc/miagrodskyresume.html

Comfort - 5

**Comment by jshawl** [comment]
:+1: Looks great! Please include completeness out of 5 as well in the future
