### ISSUE TITLE
Thom Householder Resume - HTML Only

### ISSUE THREAD

**Issue by ghost** [ga-dc/html_resume#84]
https://htmlpreview.github.io/?gist.githubusercontent.com/thomhouseholder/cc01b001c302d56e9c19/raw/c7388a1f714c766a7fcfdb8ed913efb927ddac4a/thomhouseholder.html

Always find myself tinkering with styles, probably too much for my own good!

**Comment by jshawl** [comment]
:+1: Looks great!!

In the future, please include comfort and completeness out of 5
