### ISSUE TITLE
Shawn Campbell Resume HTML Only

### ISSUE THREAD

**Issue by ghost** [ga-dc/html_resume#86]
https://gist.github.com/46b2476ae148e738e35c

Comfort - 3 many tags are unfamiliar but I am confident I can look things up as I go.

Completeness - 6 Apologies if I went overboard with the profile picture. I just figured this is for a future role as a Developer and I wanted to gear the layout towards the feel of a responsive website, rather than a resume on paper. If you want me to delete it - just let me know.

Comments: Prior to this I would have relied on UL, LI for most lists. I am new to the DL, DT, DD tags but they seem to work nicely on a resume layout. I added an image and I was confused when the html img src tag didn't require the .jpg file type.

**Comment by amaseda** [comment]
:+1:

• By all means, go all out! I can't see the picture myself since I don't have that file on my computer.
• Have never used the `dl` tag myself - very cool!
