### ISSUE TITLE
Brendan Lewis html_resume

### ISSUE THREAD

**Issue by lewis2ba** [ga-dc/html_resume#87]
https://gist.github.com/lewis2ba/186e0194c35c7a8b2500

https://gist.githubusercontent.com/lewis2ba/186e0194c35c7a8b2500/raw/bf1581c3652a1484cbede6b352eeb5757aa96e63/html_resume.txt

completeness 4/5
comfort 3/5
My resume needs some work and while I think I understand the h1-h6 tags I'm not sure I know when and where to use these and when and where to use the `<div class = "">` tags or when to use `<p>` instead of the other tags

Thanks!

Edit:
Tried hw again with `<div class = "">` tags as well as some h tags, I think it went better this time and probably would be easier when CSS is added.

https://gist.github.com/lewis2ba/e204a53dbc6445eda360

https://gist.githubusercontent.com/lewis2ba/e204a53dbc6445eda360/raw/a239bf3c493178dc60bc22a2a7a9dcb08753aa55/html_resume2.txt

**Comment by RobertAKARobin** [comment]
`<p>` has some semantic value, as in: "this is a few sentences of text on a particular topic." `<div>` really doesn't have any semantic value at all. It's supposed to be used when you can't find a better element. It's also two characters less to write!
