### ISSUE TITLE
...

### ISSUE THREAD

**Issue by ghost** [ga-dc/html_resume#88]
Web page here:
http://htmlpreview.github.io/?https://gist.githubusercontent.com/lizjoxx/ad371b7a93038068946a/raw/7d395fbc03b92ea584a5ce689411ba3a1973881a/LizResume.html

HTML here:
https://gist.githubusercontent.com/lizjoxx/ad371b7a93038068946a/raw/7d395fbc03b92ea584a5ce689411ba3a1973881a/LizResume.html

Feeling good about this homework. Wishing I could use styles!!!

**Comment by jsm13** [comment]
:+1:  Really nice job on this. Glad you're excited about CSS! Everything looks good. You might want a main element to hold everything between the header and footer and you may also want to add some classes as you get into styling.

If you would be able to add comfort and completeness levels on a scale from 1 to 5 to future homework submissions it is really helpful. Could you also please add a photo and name to your GitHub profile? Thanks!
