### ISSUE TITLE
HTML Resume Homework

### ISSUE THREAD

**Issue by dan-ator** [ga-dc/html_resume#89]
https://gist.github.com/ceae3bc3464705e4032e.git
https://htmlpreview.github.io/?gist.githubusercontent.com/dan-ator/ceae3bc3464705e4032e/raw/1287bcfcd83c9807b1f54c4f5946df8846b55e8e/gistfile1.txt

comfort: 4
complete: 5

**Comment by adambray** [comment]
Looks good!
