### ISSUE TITLE
HTML Resume Exercise 6.29.15

### ISSUE THREAD

**Issue by karldonus** [ga-dc/html_resume#9]
https://gist.githubusercontent.com/karldonus/19a3ea0292e8e275731d/raw/716666f7a5b82143ea1c2fcec9907bd932784dfd/gistfile1.html

Comfort: 4/5
Completeness: 5/5

Observations: 
1. I used a HECK of a lot of span & div classes b/c of how my resume is formatting intensive. While labor intensive now, I'm sure it will make formatting in CSS down the road MUCH easier.
2. Span vs. Div caused me a bit of trouble initially, resulting in me having to re-do a lot. Woops. Figured it out in the end. Won't make the same mistake twice.
3. Text edit is painful (when it comes to indenting compared to Sublime Text2)...but it makes me appreciate these programs (Sublime/Atom/etc) even more.
4. W3 Verify is AWESOME. It caught about a half dozen typos (errand tags, etc). Whoever invented it deserves a high-five.

**Comment by RobertAKARobin** [comment]
Instead of having a bunch of `<div class="job_info">`, just have one `<section class="job_info">` with a bunch of `<div>` inside it. You can select them in CSS with `.job_info>div`.
