### ISSUE TITLE
Chris Kibble Resume

### ISSUE THREAD

**Issue by ckib16** [ga-dc/html_resume#90]
## Part 1

Here is my gist - 
https://gist.github.com/ckib16/f4b176f6fd552a0d8422

Comfort 5/5
Completeness 5/5
No questions
## Part 2

I'd like to request that I not change my current github.io page. I've already used up my free github.io page as a lead page for a freelance service I was running. I'd like to keep it as-is so I don't have to change my domain name re-direct. I have no questions about using the github free hosting service.

**Comment by RobertAKARobin** [comment]
:+1:
