### ISSUE TITLE
Resume Homework

### ISSUE THREAD

**Issue by roshanad** [ga-dc/html_resume#93]
https://gist.github.com/roshanad/64dd999405297e686485

Comfort: 4
Completeness: 5

Comment: 
When I tried to see html from raw it didn't load...
htmlpreview.github.io/?https://gist.githubusercontent.com/roshanad/64dd999405297e686485/raw/ae66d526ef3144b0415bd25e7525bf86c783962e/roshana.html

**Comment by ebirving** [comment]
That's really weird...I'm getting the same error. Your HTML does validate, though, so I'd say don't worry about it. Nice work!

**Comment by ebirving** [comment]
👍
