### ISSUE TITLE
Brendan Mahoney Resume Homework

### ISSUE THREAD

**Issue by BMahoney08** [ga-dc/html_resume#95]
https://gist.github.com/BMahoney08/61b7efbfa3dbff8e81a6

Comfort Level - 5 of 5
Completeness - 5 of 5

Code to review - I left out a "header", "main", and "footer" section, is this something an employer would ding me for?

**Comment by RobertAKARobin** [comment]
Nah. Not unless you have `<div class="header">` instead of `<header>`.
