### ISSUE TITLE
Resume_Mati.Amin

### ISSUE THREAD

**Issue by matiamin** [ga-dc/html_resume#98]
Comfort 4
Completeness 4

https://gist.github.com/matiamin/44f6b830e566442c547b

Thanks!

**Comment by adambray** [comment]
Hey Mati,

This looks good! My main suggestion would be to try to find other tags that have more meaning than just 'divs'. E.g. use of `<section>`,  `<main>` and other tags would help improve the markup.

Also, note that you don't need to indent your `<ul>` tags an extra level after your `<h2>` tags.

Adam
