### ISSUE TITLE
Armani Hall's Resume

### ISSUE THREAD

**Issue by ArmaniH** [ga-dc/html_resume#99]
[Link to Code](https://gist.githubusercontent.com/ArmaniH/e55d91ae2e17277438ac/raw/b9425d693af77ad22e409daba6f0a43f6468aade/Armani's%2520Resume)

[Link to Resume](https://htmlpreview.github.io/?https://gist.githubusercontent.com/ArmaniH/e55d91ae2e17277438ac/raw/b9425d693af77ad22e409daba6f0a43f6468aade/Armani%27s%2520Resume)

Comfort - 7/10
Completeness - 9/10

**Comment by jshawl** [comment]
Excellent! :+1: In the future, please rate comfort/completeness out of 5
